name: delete
on:
  workflow_dispatch:

  schedule:
    - cron: 0 8 * * *

jobs:
  del_runs:
    runs-on: Ubuntu-20.04
    name: delete-workflow-runs
    steps:
    
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}       
          retain_days: 0.1
          keep_minimum_runs: 0
